### PR TITLE
remove "Future" chapter because it was outdated

### LINKED ISSUE #2294: Outdated Media Future
[Modelica.Media.UsersGuide.Future](http://doc.modelica.org/help/Modelica_Media_UsersGuide.html#Modelica.Media.UsersGuide.Future) speaks about future version 3.1 of Modelica.Media and a beta-release in 2009. This information clearly is obsolete and shall be either removed or updated.

### PR DESCRIPTION
**Pull request by Double-A-92**
Resolves #2294 Outdated Media Future

### CODE REVIEW

**Comment by HansOlsson** [comment]
To me this change looks good - but it leads to another question:  what happened to the proposed future changes?

- Are they already done? I could not find them in release notes.
- Still planned for the future? If so, can we have links to them here?
- Or cancelled?

**Comment by thorade** [comment]
Is this related to #85 and https://doi.org/10.3384/ecp15118653 ??

**Comment by MartinOtter** [comment]
I think most of the described features are already available in MSL (Hubertus should confirm)

**Comment by hubertus65** [comment]
Clearly ok from my side to merge this, this is simply an outdated and forgotten piece of documentation. Re Martin: No, this capability is not yet in Modelica.Media, we never had proper multi-component multi-phase support. But changes would require a major new release of MSL since I see no way to make this fully backward compatible.

**Pull request merged**
