### PR TITLE
clarify linearity of Vector.interpolate

### PR DESCRIPTION
**Pull request by pierre-haessig**
many formulations are possible to clarify that Vector.interpolate is linear. This is a minimalistic proposition: just adding and adverb in the first sentence.

### CODE REVIEW

**Comment by pierre-haessig** [comment]
I'm not familiar what is the development workflow of MSL, and it seems that Trac is used more than Github pull requests, so here is the corresponding ticket: https://trac.modelica.org/Modelica/ticket/2068

**Comment by tbeu** [comment]
Will be this GitHub rep in the future but is Trac+ Svn right now.

**Comment by sjoelund** [comment]
That is because the git repository is a mirror of the subversion repository. MSL is in the process of preparing to move to GitHub though
On Sep 22, 2016 16:36, Pierre Haessig <notifications@github.com> wrote:I'm not familiar what is the development workflow of MSL, and it seems that Trac is used more than Github pull requests, so here is the corresponding ticket: https://trac.modelica.org/Modelica/ticket/2068

**Comment by pierre-haessig** [comment]
Fine. Thanks for the feedback. I'll close the PR for now, and then somebody with commit right on SVN can push this in a future release (I saw that the ticket on Trac was marked for *MSL_next-MINOR-version*).

**Comment by KevinXYY** [comment]
Wanna unsubsidized.thanks!:-)

Sent from my Sony Xperia™ smartphone

---- Martin Sjölund wrote ----

**Comment by thorade** [comment]
@KevinXYY Did you mean you want to unsubscribe?
You have to do that yourself by clicking the "Unwatch" button in the top right corner of this page.

**Pull request closed without merging**
