### PR TITLE
Move LogFrequencySweep from ComplexBlocks to Blocks

### PR DESCRIPTION
**Pull request by beutlich**
refs #2157: Move LogFrequencySweep from ComplexBlocks to Blocks

### CODE REVIEW

**Comment by tbeu** [comment]
This only was a test of the GitHub Reviewer feature.

**Comment by MartinOtter** [comment]
This is a non-backwards compatible change (moving a block from one library to another one). This means that existing models using this block will no longer work. As long as we have not yet decided that conversion scripts can be used, we should not perform such changes (a pre-requisite is that the tool vendors support the conversion annotations introduced in Modelica 3.4).

**Comment by beutlich** [comment]
> This is a non-backwards compatible change (moving a block from one library to another one). 

For that reason, the milestone is set to [MSL_next-MAJOR-version](https://github.com/modelica/Modelica/milestone/4), which is defined as the next (**not yet specified**) major version which is non-backward compatible and (might) need a conversion script.

**Comment by beutlich** [comment]
Clsoing after @AHaumer's https://github.com/modelica/Modelica/issues/2157#issuecomment-355080017.

**Pull request closed without merging**
