### PR TITLE
Hans olsson patch 2

### PR DESCRIPTION
**Pull request by HansOlsson**
Solve #2152 (Removing deprecated Text-attributes).

Log of action:
**updateModelicaAnnotations("Modelica",changeLinePattern=false,orderBitmapExtent=false, removeTextDeprecated=true)**
 [LogOfAction.txt](https://github.com/modelica/Modelica/files/784035/LogOfAction.txt)

(Some other lines are changed as well, primarily to not have the annotation on a separate line. And all line endings are messed up.)

### CODE REVIEW

**Comment by dietmarw** [comment]
Here another tip, you can simply attach files by dragging them into the text field.

**Comment by HansOlsson** [comment]
@dietmarw
> Here another tip, you can simply attach files by dragging them into the text field.

I don't see exactly what you mean - especially how it would be an improvement. 
I dragged the files into the big field in the middle - but the problems were two-fold: bad line endings due to something with the upload and that I had to do it once per directory (the file-names are not necessarily unique).

(Anyway I just experimenting with the different variants of editing, and will next time see if it works better by just pushing locally to a branch.)

**Comment by dietmarw** [comment]
I was talking about the log file only you pasted here.

**Comment by HansOlsson** [comment]
Ah, I see - as far as I recall it was just the log from the command - not a log-file; so I just copy-pasted it.

**Comment by dietmarw** [comment]
Yes and pasting the whole thing here made the ticket/pull-request hard to read. That's why one should normally either [paste them as gists](https://gist.github.com/) or simply attach them as file. It's just an improvement on readability really.

**Comment by HansOlsson** [comment]
@dietmarw 
I now understand your point: the texts for issues/pull-request should be kept to a few lines - and any additional information should be added as external file(s); because that is more usable with the GitHub web-interface (similarly editing Modelica files in the browser as I did for #2178 is also awkward). 
However, such guidelines should be described directly.

**Comment by thorade** [comment]
github help describes what files can be attached to issues or pull requests and how:
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
One important differrence is that these files will NOT become part of the repository and its git history,
so attaching png and docx to issues is fine, commiting them to the repository will bloat the history.

Or for text files, using a gist as Dietmar suggested is also good.

**Pull request merged**
