### PR TITLE
Add optional reset to Integrator and LimIntegrator

### PR DESCRIPTION
**Pull request by beutlich**
See #2316.

### CODE REVIEW

**Comment by beutlich** [comment]
The one question I have is if it fits in Modelica.Blocks.Continuous?

**Comment by beutlich** [comment]
@modelica/map-lib-write Any feedback?

**Comment by beutlich** [comment]
Yes, I implemented Reset&Hold behaviour. Which option seems preferable?

1. Add Reset behaviour only.
1. Add Reset&Hold behaviour (as is), but improve documentation. The user still can use Modelica.Blocks.Logical.Change (and similar blocks) to model plain Reset behaviour.
1. Add new Boolean parameter hold and have der(y)=if localReset and hold then 0 else k*u

**Comment by HansOlsson** [comment]
I would prefer to only add reset. 
It seems possible to "hold" by using Modelica.Blocks.Logical.Switch for the input (connected to a constant 0) - which makes "hold" sort of orthogonal from "reset".

Combining reset and hold with a set-input seems to be complicated: if the set-input is time-varying it seems as if the "held" value should change to match that; that is not implemented and seems unnecessarily complicated.

**Comment by beutlich** [comment]
Implementing only the Reset behaviour makes it possible to simply __extend__ a IntegratorWithReset from Integrator and put it anywhere else in the library (which was impossible with the Hold behaviour on board).

**Comment by beutlich** [comment]
I removed the hold part of the resettable integrator and added 3 simple test models of a self-resetting integrator, a reset&hold integrator and a limiting resettable integrator. OK for you to merge?

**Comment by HansOlsson** [comment]
> I removed the hold part of the resettable integrator and added 3 simple test models of a self-resetting integrator, a reset&hold integrator and a limiting resettable integrator. OK for you to merge?

That seems ok, except  I couldn't find the version above.

**Comment by beutlich** [comment]
> That seems ok, except I couldn't find the version above.

What do you mean by "version above"? My previous commit using reset+hold? That commit was removed by `git commit --amend` and `git push --force`.

**Comment by HansOlsson** [comment]
> What do you mean by "version above"? My previous commit using reset+hold? That commit was updated by  git commit --amend  and  git push --force .

Yes, and now I see it, and it seems ok. 

I was just confused that there was no new commit listed for this.

**Comment by beutlich** [comment]
OK, thank you for your review @HansOlsson.

**Comment by beutlich** [comment]
I compared Buildings.Utilities.Math.IntegratorWithReset vs. Modelica.Blocks.Continuous.Integrator in the example model Buildings.Utilities.Math.Examples.IntegratorWithReset and can confirm, that both integrators give identical results.

**Comment by MartinOtter** [comment]
A slight drawback is that the icon of the "set" connector is at the place of %name, so the instance name and the connector icon overlap. It would be better to place the "set" connector icon to the "left", above the RealInput u connector.

**Comment by beutlich** [comment]
> A slight drawback is that the icon of the "set" connector is at the place of %name

It also happens for gains with some more digits.
int

Actually I wanted the set and reset input connectors to match the vertical "reset" line by intention.

**Comment by MartinOtter** [comment]
The strings "%name" and "k=%k" could be "right justified" a little bit "left" to "reset". In this case it would be guaranteed that no overlapp occurs

**Comment by beutlich** [comment]
The "%name" is inherited from Modelica.Blocks.Icons.Block. It has the same (horizontal) width from -150 to 150 as the "k=%k" string. Not that easy to change then.

**Pull request merged**
