### PR TITLE
Make use of groupImage to help understanding block parameters

### PR DESCRIPTION
**Pull request by dietmarw**
This commit makes use of the new `groupImage` annotation.
It simply places the already present image from the documentation side by side
with the parameters. 
This simplifies the usage and understanding of parameter's meaning to a large degree.

### CODE REVIEW

**Comment by beutlich** [comment]
Nice idea. I would prefer to have PNGs with an alpha channel in order to better support transparency on non-white backgrounds. See Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.Components.PermeanceActuator.N and [MovingCoilActuator_dimensions.png](https://github.com/modelica/Modelica/blob/master/Modelica/Resources/Images/Magnetic/FluxTubes/Examples/MovingCoilActuator/MovingCoilActuator_dimensions.png) for an example.

**Comment by sjoelund** [comment]
What about black backgrounds?

**Comment by dietmarw** [comment]
I've made the PNGs now with transparent backgrounds. I can not think that black backgrounds are relevant.

**Comment by beutlich** [comment]
Looks poor on black background.

permeanceactuator1

**Comment by dietmarw** [comment]
Right. So white background would be the safe (but uglier) choice. I'll see what the LO @MartinOtter would prefer. I can easily revert the transparency again.

**Comment by beutlich** [comment]
Anyway, transparency should be consistent then troughout the MSL.

**Comment by dietmarw** [comment]
I agree that it has to be consistent. But I don't think we need to change all images right now but start with all images that are used as `groupImage`.

**Comment by HansOlsson** [comment]
With non-transparent image background it will look somewhat bad on all backgrounds in parameter-dialog - except the one corresponding to the image background.
With transparent image background it will look good - except when background in the parameter-dialog corresponds to the foreground color(s) of the image.

A reasonable statement would be that we say that the transparent images are assumed to work with light backgrounds. Based on that tools that want to use a dark background in the parameter-dialog could:

- Make the image background white (which will be the same as non-transparent image background)
- Create a complementary image by swapping b&w

Color-images will be more complicated

**Comment by MartinOtter** [comment]
White background of the image will always work, independent of the background of the parameter menu, even if it is black. I would therefore propose to use the first version from Dietmar with white background. 

Furthermore, a ticket should be filled for the Modelica Language to discuss how images should be provided. If transparent images should be supported, then there should be a clean process how to it so that it works for all potential backgrounds.

**Comment by sjoelund** [comment]
@MartinOtter Note that the same issues apply for example for diagram/icon layers. I believe all/most vendors choose a bright background there since the default line and text colour is black in the spec, but the dialog is usually a box from the desktop environment / OS.

**Comment by dietmarw** [comment]
FYI I've reverted the transparent PNGs again.

**Comment by HansOlsson** [comment]
> @MartinOtter Note that the same issues apply for example for diagram/icon layers. I believe all/most vendors choose a bright background there since the default line and text colour is black in the spec, but the dialog is usually a box from the desktop environment / OS.

And in the documentation layer as well. Most of the images that Dietmar modified were used in the documentation as well as the parameter-dialog.

**Comment by beutlich** [comment]
> FYI I've reverted the transparent PNGs again.

OK. Will file a new MSL issue soon to have it non-transparent everywhere then.

**Comment by MartinOtter** [comment]
Nice improvement

**Pull request merged**
