### PR TITLE
Included documentation package on terms and spelling

### PR DESCRIPTION
**Pull request by christiankral**
See #2446

### CODE REVIEW

**Comment by ceraolo** [comment]
I love Oxford dictionaries. 
But for electricity-related topics the official source is the International Electrotechnical Commission (IEC ) which publishes the International Electrotechnical Vocabulary, with, in turn is available to everyone from the Internet.
So In case of mismatch,  IEC is the official technical reference.
According to this, 
magnetomotive is ok (IEV 121-11-60)

**Comment by christiankral** [comment]
OK, let's then switch to Electropedia.

**Comment by christiankral** [comment]
However, when using Electropedia links I prefer not show search results, since the corresponding links may not work one day they change the way of querying. Instead I will use technical application terms which also demonstrate the use of the term.

**Comment by ceraolo** [comment]
I quoted IEV to find "official" terminology which should be used in MSL.
I agree that it is not wise to use links to IEV in the MSL documentation.

**Pull request merged**
