### PR TITLE
Add visualization of phasors in quasi static single phase library

### PR DESCRIPTION
**Pull request by christiankral**
In the actual implementation the library specific visualizations are located in ``Modelica.Electrical.QuasiStationary.SinglePhase.Visualization``. In case it will be decided in the future to move everything into ``Modelica.Visualization``, this may be done.

### CODE REVIEW

**Comment by AHaumer** [comment]
AFAIK the animation (quasi standardized in ModelicaServices, also supported by OMEdit) does not support text labels. I'd like to encourage Dietmar to make a proposal how to handle text labels in animations.

**Comment by beutlich** [comment]
* The MultiBody World has the x, y and z text labels built from cylinder visualizers.
* There also is a Dymola feature (and #1904 to update ModelicaServices) for texture support.

**Comment by dietmarw** [comment]
@AHaumer Sorry, I'm not a OpenModelica developer and I'm not talking about the text labels but that I simply don't see what the visualisation should look like since it does not seem to work in Dymola (and especially not in OMEdit). Hence it would be nice if @christiankral could do a short video what the intention is.

**Comment by beutlich** [comment]
Please mind that you need to load the tool-specific ModelicaServices library first when playing with the visualizers of the GitHub hosted MSL.

**Comment by beutlich** [comment]
I checked Modelica.Electrical.QuasiStationary.SinglePhase.Examples.SeriesResonance and Modelica.Electrical.QuasiStationary.SinglePhase.Examples.ParallelResonance and attached the videos (Windows Media Video) from SimulationX.

[T2219.zip](https://github.com/modelica/Modelica/files/892391/T2219.zip)

**Comment by dietmarw** [comment]
One thing that I'm missing (and I know that my students will ask for that too at once ;-) ) is some labels on the vectors. I still like to check the diagram layer visualisations before approving this.

**Comment by christiankral** [comment]
See comment of #2172.

**Pull request closed without merging**
