### PR TITLE
Rewrite Modelica.Electrical.MultiPhase.Functions.numberOfSymmetricBaseSystems

### PR DESCRIPTION
**Pull request by beutlich**
Rewrite numberOfSymmetricBaseSystems as a non-recursive one-liner (that is auto-inlined)

### CODE REVIEW

**Comment by christiankral** [comment]
Please be patient, I am considering your proposal, see https://trac.openmodelica.org/OpenModelica/ticket/4550

**Comment by sjoelund** [comment]
I fixed one issue in OpenModelica; the remaining issue is with the model: `log(m/2)/log(2)` for `m=4` is not exactly 1.0 depending on computation order (we do `1/log(2)`=1.442695040888963 and we end up with 0.999999999997 instead of 1.0; `integer()` rounds that down).

**Comment by sjoelund** [comment]
I talked a bit with @casella and I guess log((n+0.2)/2)/log(2) would fix any rounding errors. Not at a computer to check it though.

**Comment by beutlich** [comment]
Right. No point to merge it then.

**Pull request closed without merging**
