### PR TITLE
Use terms single-phase, three-phase and multi-phase consistently

### PR DESCRIPTION
**Pull request by beutlich**
See #1865. Only comments and documentation was updated.

@ceraolo FYI

### CODE REVIEW

**Comment by beutlich** [comment]
Update: Prefer multi-phase over polyphase (to match the idents).

**Comment by beutlich** [comment]
@christiankral Any preferences?

**Comment by christiankral** [comment]
Personally, I am fine with the nomenclature. Before approving the pull request, I would like to discuss this issue with @AHaumer

**Comment by beutlich** [comment]
Actually, the PR is only about consistent use of the terms single-phase, multi-phase and three-phase. Nothing new.

**Comment by ceraolo** [comment]
I like single-phase and three-phase.

In some cases your PR uses "multi-phase", evidently for consistency with the other two cases.
To multi-phase I would prefer the International Electrotechnical Vocabulary version "polyphase".
if I search polyphase on
http://dom2.iec.ch/iev/iev.nsf/welcome?OpenForm&Seq=1
I find a lot of items; if I search multi-phase I find nothing.

We must search consistency inside MSL and with the official sources, such as IEC.

So my personal preference to pursue both objectives is:

single-phase, three-phase, polyphase  (which are all used inside IEV)

**Comment by beutlich** [comment]
Argh, after all the documentation changes for #2276, this now leads to plenty of merge conflicts.

**Pull request closed without merging**
