### PR TITLE
Utilize hash macros of uthash.h v2.0.2 for ModelicaStrings_hashString

### PR DESCRIPTION
**Pull request by beutlich**
Stand-alone test model for #2250:
```mo
model T2250
  function hashString "Create a hash value of a string"
    input String string "The string to create a hash from";
    output Integer hash "The hash value of string";
    external "C" hash = test_hashString(string) annotation(Include="
#include \"uthash.h\"
#undef uthash_fatal /* Ensure that nowhere in this file uses uthash_fatal by accident */
int test_hashString(const char* str) {
    /* Compute an unsigned int hash code from a character string */
    size_t len = strlen(str);
    union hash_tag {
        unsigned int iu;
        int          is;
    } h;

    HASH_VALUE(str, len, h.iu); /* Requires uthash v2.0.2 */

    return h.is;
}");
  end hashString;

  initial algorithm 
    Modelica.Utilities.Streams.print(String(hashString("String")));
end T2250;
```

### CODE REVIEW

**Comment by beutlich** [comment]
@HansOlsson @MartinOtter What do you think about the proposed change?

**Comment by HansOlsson** [comment]
Based on the comment that the original code is also available under MIT we need to redo this. I assume we want the following:

- Keep the original GeneralHashFunctions  (no need to change or invent our own)
- Update the license comment in the code (of course)
- Add the test-case

**Comment by beutlich** [comment]
I updated the test model to incorporate the original [AP hash function](http://www.partow.net/programming/hashfunctions/index.html#APHashFunction)

```mo
model T2250
  function hashString "Create a hash value of a string"
    input String string "The string to create a hash from";
    output Integer hash "The hash value of string";
    external "C" hash = test_hashString(string) annotation(Include="
/* AP hash function macro variant of the one listed at
 * http://www.partow.net/programming/hashfunctions/index.html#APHashFunction */
#define HASH_AP(key, keylen, hashv) \
do { \
    unsigned _hb_keylen = (unsigned)keylen; \
    const unsigned char *_hb_key = (const unsigned char*)(key); \
    (hashv) = 0xAAAAAAAA; \
    unsigned int i = 0; \
    for (i = 0; i < _hb_keylen; _hb_key++, i++) { \
        hashv ^= ((i & 1) == 0) ? (  (hashv <<  7) ^ (*_hb_key) * (hashv >> 3)) : \
                                  (~((hashv << 11) + ((*_hb_key) ^ (hashv >> 5)))); \
    } \
} while (0)
#define HASH_FUNCTION HASH_AP
#include \"uthash.h\"
#undef uthash_fatal /* Ensure that nowhere in this file uses uthash_fatal by accident */
int test_hashString(const char* str) {
    /* Compute an unsigned int hash code from a character string */
    size_t len = strlen(str);
    union hash_tag {
        unsigned int iu;
        int          is;
    } h;

    HASH_VALUE(str, len, h.iu); /* Requires uthash v2.0.2 */

    return h.is;
}");
  end hashString;

  initial algorithm 
    Modelica.Utilities.Streams.print(String(hashString("String")));
end T2250;
```

**Comment by beutlich** [comment]
Beside the use of uthash macros I now also updated the License of the AP hash function/macro.

**Comment by beutlich** [comment]
- [x] Keep the original GeneralHashFunctions (no need to change or invent our own)
- [x] Update the license comment in the code (of course)
- [x] Add the test-case

**Comment by MartinOtter** [comment]
Yes.
(There is also a "Merge pull request", however, I do not find the code that is proposed to merged).

**Comment by beutlich** [comment]
d7abf59 and 719105b are my proposed changes.

**Comment by MartinOtter** [comment]
I thought the original hash function should be kept and only the license text changed. However, it seems you are using another hash function now (at least the code from the original hash function is deleted).

**Comment by HansOlsson** [comment]
>I thought the original hash function should be kept and only the license text changed. However, it seems you are using another hash function now (at least the code from the original hash function is deleted).

The same code is now present in a macro. using the idiom do .. while(0)

**Comment by beutlich** [comment]
> The same code is now present in a macro. using the idiom do .. while(0)

Exactly. (This offers a nice way to swap the hash function.)

**Comment by MartinOtter** [comment]
Is there a good reason to change the inplementation, and especially use a macro? 
Why not just change the license text and keep the previous implementation?
If a new implementation is used, then it is not at once obvious that the new code and the old one produces identical results.

**Comment by beutlich** [comment]
My general idea is to have the hash function replaceable (at least at C source level). This is now possible by `#define HASH_FUNCTION HASH_AP ` as uthash offers many hash functions in macro form.

**Comment by MartinOtter** [comment]
O.k. please update with your proposal (I still find it odd to change the code now; if more functionality shall be implemented, of course this is fine, but preparing for a situation in the future, often does not work as expected).

**Pull request merged**
