### PR TITLE
Merge issue2320-license aka Change to 3-Clause BSD License

### LINKED ISSUE #2320: Implement License change decision to change to BSD-3-Clause
- [x] Add LICENSE file containing standard BSD-3-Clause text to this repository (for easy visibility of the license at GitHub)
- [x] Change license comments to BSD-3-Clause in C-Sources
- [x] Change license comments to BSD-3-Clause in README.md
- [x] Remove classes that declare ModelicaLicense2 (and accept breaking backward compatibility)
- [x] Remove links to ModelicaLicense2
- [x] Change license comments to BSD-3-Clause in Modelica files

### PR DESCRIPTION
**Pull request by beutlich**
Thanks to substantial work of @jbgohl the feature branch issue2320-license is able to get merged to finally close #2320. See also #2372 for a discussion.

@modelica/map-lib-write @adeas31 @adrpo @AHaumer @andreas-junghanns @bernhard-thiele @casella @christiankral @d-hedberg @DagBruck @dietmarw @ECClauss @GallLeo @HansOlsson @harmanpa @hubertus65 @jespermattsson @kristinmajetta @MartinOtter @mtiller @mwetter @rfranke @sjoelund @svorkoetter @ThomasBoedrich @wischhusen @ziske Please comment and give your OK as library officer or contributor.

TODO:
- [x] Copyright disclaimer as single line in new file LICENSE
- [x] Link to https://modelica.org/licenses/modelica-3-clause-bsd in Modelica files
- [x] Clarify copyright disclaimer: Modelica Association or individual authors?

### CODE REVIEW

**Comment by beutlich** [comment]
Since only 15 reviewers can be set I decided to remove all again. So please give feedback as ordinary comment.

**Comment by thorade** [comment]
Would it make sense to have a CLA at some point?

github and SAP have developed a very user-friendly solution here:
https://cla-assistant.io/
https://github.com/cla-assistant/cla-assistant

github uses that for their own CLA:
https://cla.github.com/

It will check for all Pull Request whether the contributor has signed the CLA, and blocks merging until it is signed. Signing the CLA has to be done only once, and is very simple (just two or three clicks).
A csv list of contributors can be imported, so that they don't have to sign the CLA again;
and a list of contributors who have signed can be exported at any time.

**Comment by christiankral** [comment]
I hopefully did not mess up the review of @dietmarw (sorry, in case I did)

**Comment by beutlich** [comment]
> I hopefully did not mess up the review of @dietmarw (sorry, in case I did)

Looks all good. Thanks.

**Comment by HansOlsson** [comment]
I don't have a major objection (I think that 3rd clause is redundant, but that is unproblematic) - but I would have preferred to have the 3-clause BSD on our own web-site - specialized with year and copyright holder, and reference that instead of the generic https://opensource.org/licenses/BSD-3-Clause (our web-page can then reference https://opensource.org/licenses/BSD-3-Clause).

Relying on the exact names for external sites may cause unexpected issues, I noticed that for MathJax.

**Comment by HansOlsson** [comment]
Of course, we need to verify the CLA together with this license change with our lawyers. I believe that should be done before merging this PR.

**Comment by beutlich** [comment]
I update the branch and resolved the (trivial) merge conflict. (And I noticed that I created the PR from my own repo instead of the feature branch I created at the official repo - anyway).

> Of course, we need to verify the CLA together with this license change with our lawyers. I believe that should be done before merging this PR.

So what are the next steps? Ask DS lawyers or set up the CLA assistent as proposed by @thorade?

**Comment by HansOlsson** [comment]
> So what are the next steps? Ask DS lawyers or set up the CLA assistent as proposed by @thorade?

Both steps seems good.
Note that it is not only DS lawyers, but get all relevant companies and organizations to sign the CLA. I assume this will take some time - so we need to start soon.
The CLA assistant is primarily to make it easy for new contributors. 

One issue is what to before companies have signed the CLA; I don't think we can activate the CLA assistant, but it would be good to get new contributors to sign the CLA without impacting the signing for existing contributors.

**Comment by beutlich** [comment]
The CLA is available (as MAP-SSP and MAP-FMI members/contributors already signed it). If I am not wrong the idea was to have one general CLA at the MA in order to avoid individual MAP-related CLAs, right?

Thus, what is the problem with setting up the CLA assistent (with the MA CLA), let the current MAP-LIB members and external contributors sign it? Signing needs to be done as user not as organization.

**Comment by HansOlsson** [comment]
> The CLA is available (as MAP-SSP and MAP-FMI members/contributors already signed it). 

I thought that the MAP-FMI members/contributors only signed a (slightly) different CLA for FMI, but I might be mistaken.

> If I am not wrong the idea was to have one general CLA at the MA in order to avoid individual MAP-related CLAs, right?

Yes, we don't want this mess.

**Comment by MartinOtter** [comment]
The FMI group signed a CLA that contained FMI specific terms (e.g. how to handle past contributions to FMI 1.0 and 2.0).

**Comment by HansOlsson** [comment]
> The FMI group signed a CLA that contained FMI specific terms (e.g. how to handle past contributions to FMI 1.0 and 2.0).

The first obvious question is: is the Modelica Association CLA ready and sent to companies for signing? I thought it was, but I cannot easily find the final text. @hubertus65 ?

And I also got some indication that MAP-SSP may have their own CLA instead of using the common CLA. @JochenKoehler - can you clarify?

**Comment by HansOlsson** [comment]
I would also propose two changes to this pull request:
1. As previously indicated reference a local MA-copy with year and copyright holder, instead of https://opensource.org/licenses/BSD-3-Clause - it is tidier (the current one reminded me of Sam Vimes) and avoids an external dependency.
2. Actually reference the CLA as well in MSL (once - and it could just be a link to the web). The CLA-assistance has benefits, but in case someone downloads MSL it would be good if they saw a reference to the CLA in case they want to contribute.

**Comment by beutlich** [comment]
> I would also propose two changes to this pull request:

@HansOlsson Do you manage to make the proposed changes? You simply can update this pull request by pushing to to the issue2320-license branch on [beutlich/Modelica](https://github.com/beutlich/Modelica). Thanks!

**Comment by hubertus65** [comment]
First, we decided at the MA meeting to separate the CLA from getting the new license in: one is cleaning up our old sins (important), the other is about implementing a recent decision on going forward, and if we create an unneeded dependency we just get to analysis paralysis. I will check on the draft text for the CLA, which I believe should be final and sent out asap, that is true.

**Comment by HansOlsson** [comment]
> First, we decided at the MA meeting to separate the CLA from getting the new license in: one is cleaning up our old sins (important), the other is about implementing a recent decision on going forward, and if we create an unneeded dependency we just get to analysis paralysis. I will check on the draft text for the CLA, which I believe should be final and sent out asap, that is true.

Thanks for the clarifying the status (even if I think both are "cleaning up old sins").

I must have missed this decision about decoupling the CLA and License-change - I thought the CLA was needed to allow MA to cleanly change the license.

Obviously we will have to wait with referencing the CLA until it is ready.

**Comment by sjoelund** [comment]
> I must have missed this decision about decoupling the CLA and License-change - I thought the CLA was needed to allow MA to cleanly change the license.

Which is why you can implement the CLA first. Get people to sign it and once that is done, implement the license change. The CLA does not need to be tied to any license (just give MA a copyright license to the work).

**Comment by HansOlsson** [comment]
> Which is why you can implement the CLA first. Get people to sign it and once that is done, implement the license change.

I agree that would be unproblematic.
But I interpreted @hubertus65 as saying that CLA and license change were truly separate so that we could do them in any order.

**Comment by MartinOtter** [comment]
Formally, one should first sign the CLA and then change the license in the MSL. Anyway, lets start the signing of the CLA as soon as possible. 
On the other hand, we did not have a CLA before and made decisions by voting. So, for me it would be also o.k. to already utilize the BSD license in the next version of MSL. If the CLA signing starts soon, I will try to get it soon signed by DLR and then the DLR part of MSL is fine. So, please give organizations like DLR some time for signing, say 1 month, and only afterwards change the license.

**Comment by HansOlsson** [comment]
> @HansOlsson Do you manage to make the proposed changes? You simply can update this pull request by pushing to the issue2320-license branch on beutlich/Modelica.

I was planning to and added https://modelica.org/licenses/modelica-3-clause-bsd as preparation.
(so that it can be referenced instead of https://opensource.org/licenses/BSD-3-Clause ).
I then noticed that a license already existed https://github.com/beutlich/Modelica/blob/issue2320-license/LICENSE but there were two differences:

1. It doesn't have Modelica Association as copyright holder, but all contributors.
2. It is not the exact text of https://opensource.org/licenses/BSD-3-Clause - but at least includes the redundant text "all rights reserved" - https://en.wikipedia.org/wiki/All_rights_reserved

Assuming I understand how to handle different remotes, I could change these two items - but I wanted confirmation that we want Modelica Association as copyright holder, and no-one else; and less importantly that we use text for BSD 3-clause from https://opensource.org/licenses/BSD-3-Clause with text replacing the `<....>`

**Comment by beutlich** [comment]
> 1. It doesn't have Modelica Association as copyright holder, but all contributors.

That is the question I was raising at https://github.com/modelica/Modelica/issues/2320#issuecomment-328016673. Once we have the CLA we can change the copyright holders from the individual contributors to the MA.

> 2. It is not the exact text of https://opensource.org/licenses/BSD-3-Clause - but at least includes the redundant text "all rights reserved" - https://en.wikipedia.org/wiki/All_rights_reserved

The BSD licenses are the only ones I saw around with "All rights reserved" in it. See also [https://en.wikipedia.org/wiki/BSD_licenses](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22BSD_License_2.0.22.2C_.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29). Since we had it already this way in the MSL C-Sources I simply decided to keep it this way.

**Comment by HansOlsson** [comment]
> That is the question I was raising at #2320 (comment)#2320 (comment), Implement License change decision to change to BSD-3-Clause. Once we have the CLA installed in the process we can change the copyright holders from the individual contributors to the MA.

This makes no sense to me. Modelica Association is sort of taking ownership of the work - and changing the license condition while keeping the original copyright holders - and without even adding Modelica Association as copyright holder.
In some cases someone can sublicense it under different conditions. We could view it as that case - if Modelica Association also had the license.

When the CLA is in place then Modelica Association both have the copyright - and can change the license conditions.

If we **still** want to do it I would propose to add Modelica Association first in the list, and then after CLA is in place remove the remainder. Another possibility would be to temporarily use something along the lines of
https://github.com/mumble-voip/mumble/blob/master/LICENSE and just reference the authors.

I can add Modelica Association before the other contributors - and update the web-page to be consistent. I just wanted to confirm this.

**Comment by beutlich** [comment]
@HansOlsson I agree with you and think, we all can learn from FMI once again, where it simply reads
```
   Copyright © 2011 MODELISAR consortium,
               2012-2013 Modelica Association Project "FMI"
               All rights reserved.
```
The mumble way of listing all individual contributors is a lot of work, but we even fail to keep our own contributor's list up-to-date, see [doc.modelica.org](http://doc.modelica.org/help/Modelica_UsersGuide.html#Modelica.UsersGuide.Contact) or #2287.

**Comment by hubertus65** [comment]
First, the MFI case is different, that was a planned and deliberate transfer of ownership and copyright from one organization to another. We don't have that for any code in MSL, AFAIK. 

We have to distinguish here between copyright and ownership. The problem with the current status is that we cannot, and another problem is that copyright follows different legal concepts in different countries. 

Copyright has basically two parts: the "Creator's rights", which in Germany and Sweden are unalienable, and the "Usage rights", for which we, the MA, in any case, assume that they are with the MA (but most likely not exclusive, the author still has them). 

In the US and UK, there is no such distinction, and you can completely transfer all your rights to someone else. Due to the prevalence of English, and so many US-based open source project (anything government funded has to become open source), most lay people interpret Copyright in software in the US way.    

What the CLA does is that it makes sure that ownership of all code is with the MA, and a license is given back to the creator, so that they also have usage right. The legally safe way of doing it. 

However, the MA has always assumed and acted as if at least had a license by the creator to all rights necessary, even sublicensing under another license: we have already changed the license once, and we did it back then without a written agreement by all factual code writers and holders of the "Creator's right". 

So I disagree with Martin here: the CLA is a clean-up which we should do, but we will not be able to get it for all code, no matter what. We can merge as is and should agree on the formalities. 

I think Hans' version of a local copy at modelica.org, with the copyright as the MA copyright, is the right way to go. We should collect, recognize and promote all contributors at some place, but not in the license or copyright clauses. I think this is just confusing from a global point of view: We assume that the MA has all usage rights in any case, and, assuming we use the Continental European copyright definition, the contributors hold their unalienable creator's rights (Urheberrechte), but spelling that out is misleading for e.g. any US lawyer and will just call us trouble and harm. 

From my point of view: we should make sure to point to https://modelica.org/licenses/modelica-3-clause-bsd, use the same "Copyright © 1998-2017 Modelica Association" everywhere, merge and move on! BTW: I pinged Martin to take the next steps in the CLA process.

**Comment by hubertus65** [comment]
I just saw that we have ton's of copyright notes with something like Copyright © 1998-2016 Modelica Association, Anton Haumer, Christian Kral and AIT. That is fine for now and works with usage rights on both sides, and Creator's rights always with Individuals. Parties that have signed the CLA should be removed from this though, since then the copyright in the US meaning is with the MA, and the signer holds a (very broad) license. Of course, individual signers still hold creator's rights (but not companies or institutions). So, for correctness, companies, and institutions should be removed from the copyright phrase after they sign the CLA, they have no part of copyright after that also with the Continental European copyright definition. This means that I think we are good to go for now and I'll approve the pull request.

**Comment by hubertus65** [comment]
There are many place where we refer to the abstract license conditions with a link to https://opensource.org/licenses/BSD-3-Clause. I think that is a good way to do it, since we refer to the "official" open source conditions. This is done this way for all sub-library level license references. On the top level and in our documentation classes I think we should point to our variant at  https://modelica.org/licenses/modelica-3-clause-bsd, but I don't feel strongly about that.  But, Hans: I'd remove the redundant sentence "3-clause BSD with Modelica Association as copyright holder:" from https://modelica.org/licenses/modelica-3-clause-bsd and make the title "3-clause BSD License for the Modelica Association" or something like that.

**Comment by beutlich** [comment]
To keep it simple and consistent https://modelica.org/licenses/modelica-3-clause-bsd should be really identical to https://github.com/beutlich/Modelica/blob/issue2320-license/LICENSE to have a single source of truth only.

**Comment by HansOlsson** [comment]
> But, Hans: I'd remove the redundant sentence "3-clause BSD with Modelica Association as copyright holder:" from https://modelica.org/licenses/modelica-3-clause-bsd and make the title "3-clause BSD License for the Modelica Association" or something like that.

Ah, remove the description text and update the title; done that.

I assume keeping the final sentence was ok, the text "Modelica Association as copyright holder" is a bit redundant at the end as well and could be removed - but it was more by saying exactly what is changed it indicates that nothing else is changed.

>To keep it simple and consistent https://modelica.org/licenses/modelica-3-clause-bsd should be really identical to https://github.com/beutlich/Modelica/blob/issue2320-license/LICENSE to have a single source of truth only.

I agree that they should be identical - and would prefer to do that by copying modelica-3-clause-bsd to LICENSE (well, except removing html-markup), since we can trace it back to https://opensource.org/licenses/BSD-3-Clause

**Comment by thorade** [comment]
A minor sidenote: github will recognize and display the license in the overview bar:
https://github.com/blog/2252-license-now-displayed-on-repository-overview
That will only work if the text is unaltered; not sure about line breaks, additions etc.

**Comment by beutlich** [comment]
> A minor sidenote: github will recognize and display the license in the overview bar:
https://github.com/blog/2252-license-now-displayed-on-repository-overview
That will only work if the text is unaltered; not sure about line breaks, additions etc.

Thanks. I usually do care about his, but only now tested at https://github.com/tbeu/Modelica. In order to recognize the license correctly, the copyright holders need to be on a single line.

@HansOlsson The default 3-clause BSD license generated by GitHub contains that "All rights reserved" line. See https://github.com/tbeu/bsd3/blob/master/LICENSE. Can you please add it at https://modelica.org/licenses/modelica-3-clause-bsd. Thanks.

**Comment by beutlich** [comment]
FYI: I added the open points in the first comment.

**Comment by kristinmajetta** [comment]
approved

**Pull request merged**
